version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: inter_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investment_db
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
